### ISSUE TITLE
create docker-compose file to build, start and stop servicies.

### ISSUE THREAD

**Issue by vsysoev** [IntegraSDL/platform#1]
It should be docker-compose.yml which contains infrastructure to build, start, upgrade and stop all servicies in the platform

**Comment by n3z0xx** [comment]
Do I need to create pr or commit directly into main branch? @vsysoev

**Comment by vsysoev** [comment]
Good question! Branch of cause. I put an docker-compose file which might be used as example.

**Comment by vsysoev** [comment]
@n3z0xx I've pulled examples to master branch. We will start working with this examples. All specifics URL should be passed through environment variables and .env file. Not to put .env file to repository

**Comment by n3z0xx** [comment]
> @n3z0xx I've pulled examples to master branch. We will start working with this examples. All specifics URL should be passed through environment variables and .env file. Not to put .env file to repository
> 

Services should be same as in the example?

**Comment by vsysoev** [comment]
> > @n3z0xx I've pulled examples to master branch. We will start working with this examples. All specifics URL should be passed through environment variables and .env file. Not to put .env file to repository
> 
> Services should be same as in the example?

Yes, at first sight we need to start system with docker compose file. This will be expected result for this ticket.
